version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:

    docker: # run the steps with Docker
      - image: circleci/node:13.11.0

    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run:
                name: Clone GSN repository
                command: >-
                  git clone https://github.com/opengsn/gsn.git &&
                  cd gsn &&
                  npm install &&
                  npm run prepare &&
                  cd .. &&
                  mkdir npmprefix &&
                  npm config set prefix ./npmprefix &&
                  npm link gsn
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
